spring.application.name=demo

mysql://root:tsDSsQLCtPHXaEZZzuGsyijFFOMMYpBX@gondola.proxy.rlwy.net:33264/railway
spring.datasource.username=root
spring.datasource.password=tsDSsQLCtPHXaEZZzuGsyijFFOMMYpBX



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true